<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>minity</string>
   </array>
  <key>name</key>
  <string>minity</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.minity</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(function|macro)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.minity</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.function.minity</string>
          <key>end</key>
          <string>(?=[\x{007b}\x{0028}])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#globals</string>
        </dict>
       </array>
    </dict>
    <key>arg_expansion</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\{)(\?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.constant.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#arg_expansion__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>([\}\&quot;]|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>arg_expansion__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}\x{007b}\x{007d}\n\n]+)</string>
          <key>name</key>
          <string>variable.other.constant.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#inside_expansion</string>
        </dict>
       </array>
    </dict>
    <key>braces</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#braces__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>braces__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#statements</string>
        </dict>
       </array>
    </dict>
    <key>brackets</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#brackets__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>brackets__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#statements</string>
        </dict>
       </array>
    </dict>
    <key>conditions</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#conditions__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>conditions__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s*(?:\b(?:sort|limit|tag|nbt|type|predicate|distance|level|team|name|gamemode|scores|advancements)\b)\s*=\s*)</string>
          <key>name</key>
          <string>support.class.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s*(?:[a-zA-Z]\w*)\s*=\s*)</string>
          <key>name</key>
          <string>invalid.illegal.error.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#literals</string>
        </dict>
       </array>
    </dict>
    <key>globals</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.+)</string>
          <key>name</key>
          <string>comment.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(sssss/.+)</string>
          <key>name</key>
          <string>entity.name.function.minity</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#inside_command</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.(?:[a-zA-Z]\w*))</string>
          <key>name</key>
          <string>support.class.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\s*tag)(?!\s*@)(\s+)(\w+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\s*score)(\s+)(\w+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\s*(?:\b(?:function|macro|namespace|score|tag|var)\b))</string>
          <key>name</key>
          <string>storage.type.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(score)(\s+)((?:[a-zA-Z]\w*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(bossbar)(\s+)((?:[a-zA-Z]\w*))(\s+)(value|visible|max|players|name)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.minity</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>whitespace.minity</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>meta.object.literal.key.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:\b(?:after|else|every|and|if|import|repeat|test|then|until|unless|when|while|with|align|anchored|as|at|facing|for|in|pos|positioned|predicate|rot|rotated)\b)|(?:\b(?:in|up|down|north|south|east|west|left|right|forward|back|upward|downward)\b))</string>
          <key>name</key>
          <string>keyword.control.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:\b(?:append|delete|merge|bossbar|clear|delete|give|prepend|remove|print|say|setblock|summon|tag|untag|add|remove)\b))</string>
          <key>name</key>
          <string>keyword.control.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(eyes|feet)</string>
          <key>name</key>
          <string>keyword.control.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:(?:(?:[a-zA-Z]\w*):)?(?:[a-zA-Z]\w*)(?:/(?:[a-zA-Z]\w*))*)\s*(?=\())</string>
          <key>name</key>
          <string>entity.name.function.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#selector</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brackets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#parens</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#values</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{005b}\]\x{003a}\x{003d}\x{002c}\x{0023}\x{003c}\x{003e}\x{002b}\-\x{002a}\x{0026}\x{002f}\x{0025}\x{003f}]|\.\.)</string>
          <key>name</key>
          <string>punctuation.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\S)</string>
          <key>name</key>
          <string>invalid.illegal.error.minity</string>
        </dict>
       </array>
    </dict>
    <key>inside_command</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inside_expansion</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{007b}\n\n]+)</string>
          <key>name</key>
          <string>entity.name.function.minity</string>
        </dict>
       </array>
    </dict>
    <key>inside_expansion</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#arg_expansion</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#tag_expansion</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#selector_expansion</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#literal_expansion</string>
        </dict>
       </array>
    </dict>
    <key>inside_quotes</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\(?:[\x{005c}nrt\x{007b}]|u\d\d\d\d))</string>
          <key>name</key>
          <string>constant.character.escape.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#inside_expansion</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}\x{007b}]+)</string>
          <key>name</key>
          <string>string.minity</string>
        </dict>
       </array>
    </dict>
    <key>literal_expansion</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\{=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#literal_expansion__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>([\}\&quot;]|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>literal_expansion__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#values</string>
        </dict>
       </array>
    </dict>
    <key>literals</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\?(?:[a-zA-Z]\w*))</string>
          <key>name</key>
          <string>variable.other.constant.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brackets</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#inside_quotes</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false)</string>
          <key>name</key>
          <string>constant.numeric.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{002b}-]?[0-9]+)((?:\.[0-9]+)?)((?:[eE][0-9]+)?)((?:deg|[fdbsli])?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.minity</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:[a-zA-Z]\w*))</string>
          <key>name</key>
          <string>text.minity</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>parens</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\()(?=.*?@)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#parens__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#parens__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>parens__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#selector</string>
        </dict>
       </array>
    </dict>
    <key>parens__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((?:\b(?:in|up|down|north|south|east|west|left|right|forward|back|upward|downward)\b))</string>
          <key>name</key>
          <string>keyword.control.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#values</string>
        </dict>
       </array>
    </dict>
    <key>raw_tags</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(&lt;)((?:[a-zA-Z]\w*))(\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>whitespace.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#raw_tags__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?:(&lt;/)(?:(?=\2\b))((?:[a-zA-Z]\w*))(&gt;)|(/&gt;))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag.minity</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(&lt;/)</string>
          <key>name</key>
          <string>invalid.illegal.error.minity</string>
        </dict>
       </array>
    </dict>
    <key>raw_tags__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#literals</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#raw_tags__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=&lt;/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(&lt;/)((?:[a-zA-Z]\w*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.error.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>raw_tags__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#raw_tags</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{003c}]+)</string>
          <key>name</key>
          <string>text.minity</string>
        </dict>
       </array>
    </dict>
    <key>selector</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>((?:\b(?:nearest|closest|furthest|arbitrary|oldest|any|random)\b)\s+)?(\d+\s+)?(\@(?:(?:(?:[a-zA-Z]\w*):)?(?:[a-zA-Z]\w*)(?:/(?:[a-zA-Z]\w*))*))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#selector__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=[^\[\{.\x{0021}])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>selector__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#conditions</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.(?:[a-zA-Z]\w*))</string>
          <key>name</key>
          <string>support.class.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.)(\?(?:[a-zA-Z]\w*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.constant.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\.)(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#inside_quotes</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>selector_expansion</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\{)(?=.*@)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#selector_expansion__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>([\}\&quot;]|$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>selector_expansion__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#selector</string>
        </dict>
       </array>
    </dict>
    <key>statements</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#globals</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(function|macro)</string>
          <key>name</key>
          <string>invalid.illegal.error.minity</string>
        </dict>
       </array>
    </dict>
    <key>tag_expansion</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\{)(\.)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>support.class.minity</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#tag_expansion__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>([\}\&quot;])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.minity</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>tag_expansion__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}\x{007b}\x{007d}]+)</string>
          <key>name</key>
          <string>support.class.minity</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#inside_expansion</string>
        </dict>
       </array>
    </dict>
    <key>values</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#raw_tags</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$(?:[a-zA-Z]\w*))</string>
          <key>name</key>
          <string>variable.minity</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-&gt;)((?:[a-zA-Z]\w*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.minity</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.minity</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#literals</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
